# Generated by Django 4.1.3 on 2022-12-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("traits", "0006_remove_trait_pets"),
        ("pets", "0003_alter_pet_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="groups.group",
            ),
            preserve_default=False,
        ),
    ]
