# Generated by Django 4.1.3 on 2022-12-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_alter_pet_age"),
        ("traits", "0002_trait_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="pets", to="pets.pet"),
        ),
    ]
